name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Set environment variable '...'
        2. Run command '...'
        3. Execute query '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your environment
      placeholder: |
        - OS: [e.g. Ubuntu 20.04, macOS 12.0, Windows 11]
        - Python version: [e.g. 3.11.0]
        - aws-athena-mcp version: [e.g. 1.0.0]
        - AWS region: [e.g. us-east-1]
        - Athena workgroup: [e.g. primary]
    validations:
      required: true

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: If applicable, add error logs to help explain your problem
      placeholder: |
        ```
        Paste your error logs here
        ```
      render: shell

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Please share your configuration (remove sensitive information)
      placeholder: |
        ```bash
        export ATHENA_S3_OUTPUT_LOCATION=s3://my-bucket/results/
        export AWS_REGION=us-east-1
        # ... other environment variables
        ```
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please check the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the required information above
          required: true
        - label: I have removed any sensitive information from logs and configuration
          required: true 